### ISSUE TITLE
Your collection of type <class 'list'> cannot be handled by paginate.

### ISSUE THREAD

**Issue by michaelbukachi** [Pylons/paginate#13] opened 2018-09-07 10:52 UTC
I get this error when I try to pass a python list into the Page constructor

**Comment by stevepiercy** [comment] 2018-09-07 11:10
@michaelbukachi although we don't include a reference to it in this project, please have a look at [General Support](https://pylonsproject.org/community-support.html), and consider reaching a larger audience with your request for help.

That said, here's the [code that displays that error message](https://github.com/Pylons/paginate/blob/master/paginate/__init__.py#L249-L255). This probably means that your list is empty. What is its value?

**Comment by stevepiercy** [comment] 2018-09-07 12:19
That's a valid list, containing two dicts. How do you pass it into the constructor? Let's see some code.

Otherwise I'd suggest running a debugger on your code with a break point and inspect values to ensure they are what you expect them to be.

**Comment by ergo** [comment] 2018-09-07 15:55
Hey @michaelbukachi - I've added a test for list of dictionaries:
https://github.com/Pylons/paginate/blob/master/tests/test_paginate.py#L332 Everything appears to be working as intended

**Comment by michaelbukachi** [comment] 2018-09-08 21:27
I've figured it out. It seems passing None into the parameters of page, items_per_page raises the above error. I had to add the following snippet to as a check:
```
def paginate_list(data, args):
    page = args['page'] if args.get('page', None) else 1
    per_page = args['per_page'] if args.get('per_page', None) else 20
    new_data = Page(data, page=page, items_per_page=per_page)
    .....
```

**Comment by ergo** [comment] 2018-09-08 21:45
@michaelbukachi I'm glad you figured it out. If I may suggest something, you can do 

    page = int(args.get('page', 1))
    per_page = int(args.get('per_page', 20))
    new_data = Page(data, page=page, items_per_page=per_page)

You will achieve same effect in a shorter form.
Closing the issue.

**Closed by ergo** 2018-09-08 21:45 UTC

**Comment by stevepiercy** [comment] 2018-09-08 21:54
@ergo sounds like we need a check in https://github.com/Pylons/paginate/blob/master/paginate/__init__.py#L247 to ensure that the value passed is of type `integer` to avoid the footgun, or improve the existing TypeError message.

**Comment by stevepiercy** [comment] 2018-09-08 21:57
```python
if type(items_per_page) is not int:
    raise TypeError("items_per_page is not of type int")
```

and then a test for that.
